version: "3"

tasks:
  build:
    desc: Build the app
    deps:
      - lint
      - assets
    cmds:
      - wails build -ldflags="-s -w -H=windowsgui -extldflags '-static -static-libgcc'" -upx -clean -platform=windows/amd64
  dev:
    deps:
      - assets
    cmds:
      - wails dev
    silent: false
    env:
      DEV_MODE: true
  release:
    deps:
      - lint
      - assets
    cmds:
      - goreleaser release --clean
    dotenv: [".env"]
  release-snapshot:
    deps:
      - lint
      - assets
    cmds:
      - goreleaser release --snapshot --clean
    dotenv: [".env"]
  assets:
    cmds:
      - go-bindata assets/...
      - echo "//lint:file-ignore SA1019 Ignore it's generated" > tempfile
      - echo "//lint:file-ignore ST1005 Ignore it's generated" >> tempfile
      - cat $PWD\\bindata.go | tee -a tempfile >/dev/null 2>&1
      - mv tempfile $PWD\\bindata.go
  lint:
    cmds:
      - staticcheck
