// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetGameVersion() {
  return window['go']['main']['App']['GetGameVersion']();
}

export function List() {
  return window['go']['main']['App']['List']();
}

export function Play(arg1) {
  return window['go']['main']['App']['Play'](arg1);
}

export function PlayLocal(arg1) {
  return window['go']['main']['App']['PlayLocal'](arg1);
}

export function Remove(arg1) {
  return window['go']['main']['App']['Remove'](arg1);
}

export function RemoveLocal(arg1) {
  return window['go']['main']['App']['RemoveLocal'](arg1);
}
