// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {replay} from '../models';

export function GetGameVersion():Promise<string>;

export function List():Promise<Array<replay.Replay>>;

export function Play(arg1:string):Promise<void>;

export function PlayLocal(arg1:string):Promise<void>;

export function Remove(arg1:string):Promise<void>;

export function RemoveLocal(arg1:string):Promise<void>;
