// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function List():Promise<main.ListResult>;

export function Play(arg1:string):Promise<void>;

export function PlayLocal(arg1:string):Promise<void>;

export function Remove(arg1:string):Promise<void>;

export function RemoveLocal(arg1:string):Promise<void>;
