name: goreleaser

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: stable
      - name: Install rsrc
        run: go install github.com/akavel/rsrc@latest
      - name: Install go-bindata
        run: go install github.com/go-bindata/go-bindata/...@latest
      - name: Generate bindata.go file
        run: go-bindata assets/...
      - name: Add lint ignore to bindata.go
        run: |
          type bindata.go | Out-File bindata.temp
          echo "//lint:file-ignore SA1019,ST1005 Ignore it's generated" > bindata.go
          Get-Content bindata.temp | Out-File bindata.go -Append
          rm bindata.temp
      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@v2.4.1
      - name: Install upx
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install upx
      - name: Build the app
        run: wails build -ldflags="-s -w -H=windowsgui -extldflags '-static -static-libgcc'" -upx -clean -platform=windows/amd64
      - uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
